openapi: 3.0.0
info:
  description: |
    API docs for SSCI
  version: "1.0.0"
  title: SSCI-Web API
  contact:
    email: evenstensberg@nasa.gov

paths:
  /test:
    get:
      summary: Tests
      description: Returns a test
      responses: 
        200:
          description: Test